version: '3.8'

services:
  app-builder:
    container_name: app-builder
    build:
      context: .
      dockerfile: app_builder.dockerfile
    network_mode: host
    depends_on: []
    volumes:
      - ./output:/home/app/output
    stdin_open: true
    tty: true

  test-runner:
    container_name: test-runner
    build:
      context: .
      dockerfile: test_runner.dockerfile
    network_mode: host
    depends_on: []
    volumes:
      - ./output:/home/app/output
    environment:
      - TERM=xterm-256color
      - PACKAGE_NAME=com.companyname.basicappiumsample
    stdin_open: true
    tty: true
