version: '3.8'

services:
  android-emulator:
    container_name: android-emulator
    build:
      context: .
      dockerfile: appium_arm64.dockerfile
    network_mode: host
    privileged: true
    devices:
      - /dev/kvm
    environment:
      - ANDROID_SDK_ROOT=/opt/android-sdk
      - ANDROID_HOME=/opt/android-sdk
    command: >
      bash -c "
        echo 'Starting Android emulator...' &&
        ${ANDROID_SDK_ROOT}/emulator/emulator -avd android34-arm64 -no-audio -no-window -gpu swiftshader_indirect &&
        echo 'Emulator started successfully'
      "
    stdin_open: true
    tty: true

  appium:
    container_name: appium
    build:
      context: .
      dockerfile: appium_arm64.dockerfile
    network_mode: host
    depends_on:
      android-emulator:
        condition: service_started
    stdin_open: true
    tty: true

  app-builder:
    container_name: app-builder
    build:
      context: .
      dockerfile: app_builder.dockerfile
    network_mode: host
    depends_on:
      android-emulator:
        condition: service_started
      appium:
        condition: service_started
    stdin_open: true
    tty: true

  test-runner:
    container_name: test-runner
    build:
      context: .
      dockerfile: test_runner.dockerfile
    network_mode: host
    depends_on:
      android-emulator:
        condition: service_started
      appium:
        condition: service_started
    volumes:
      - ./output:/home/app/output
    environment:
      - TERM=xterm-256color
      - PACKAGE_NAME=com.companyname.basicappiumsample
    stdin_open: true
    tty: true